pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                bat script: '''
                    echo "I am in build step"
                    gradlew.bat build
                ''',
            label: "Building Project"
            }
        }
        stage('Test')
        {
            steps {
                bat script: '''
                    echo "I am in Test step"

                    gradlew test
                ''',
            label: "Running Unit Test Cases"
            }
        }
        stage('Static Code Analysis')
        {
            steps {
                bat script: '''
                    echo "I am in Sonarqube scan"
                ''',
            label: "Running Sonarqube Scan"
            }
        }
        stage('Build DockerImage')
        {
            steps {
                bat script: '''
                    echo "I am Building DockerImage ="

                    docker build . -t "built-docker-through-jenkins"
                ''',
            label: "Building Docker Image"
            }
        }
        stage('Publish DockerImage')
        {
            steps {
                bat script: '''
                    echo "I am Pubishing DockerImage ="
		    docker login -u=shirinniyazi -p=wakanda1@
                    docker push shirinniyazi/first_try:built-docker-through-jenkins
                ''',
            label: "Publishing Docker Image"
            }

        }
    }
    post{
    	always{
		bat script:'''
		docker logout
		'''
		deleteDir()
	}
    }
}
